#!/usr/bin/env bash
# Strategy Lab daily build — run weekdays after the close (launchd template:
# scripts/com.alex.strategylab.daily.plist fires 15:30 CT = 4:30 PM ET).
#
# Sections marked FILL IN call YOUR local generators (agentic-cron /
# market-data-brain). Everything else is ready to run. The script is
# fail-closed: if any step or validation fails, nothing is pushed and the
# previous build keeps serving.
set -euo pipefail

REPO="$HOME/repos/strategy-lab-site"   # local clone of alexreed122287/strategy-lab (per publish.sh)
WORK="$HOME/repos/strategy-lab-dashboard"  # where the builder + caches live
TMP="$(mktemp -d)"
LOG="$REPO/.daily_build.log"
trap 'rm -rf "$TMP"' EXIT
exec >>"$LOG" 2>&1
echo "=== daily build start $(date '+%F %T') ==="

# 0) Sync the site clone first - dashboard changes merge from the cloud session,
#    and an out-of-date clone would make tonight's push fail non-fast-forward.
#    index.html is always regenerated by splices below, so discarding a partial
#    copy from a previously failed run is safe.
cd "$REPO"
git checkout -- index.html 2>/dev/null || true
git pull --ff-only origin main \
  || echo "WARNING: pull failed (dirty tree or diverged) - building on local state; the push step may fail"

cd "$WORK"

# 0b) Tradier token self-heal (2026-08-15). dump_closes/robert_* PREFER
#     ~/.tradier_token over the env var by design, so a rotation that lands in
#     the canonical ~/options-platform/.env but not in this copy 401s the whole
#     build fail-closed (happened 8/12-8/14, three lost sessions). Sync the copy
#     from the canonical source whenever they differ.
#     The || true keeps a missing .env / absent key from killing the build via
#     set -e: self-heal is best-effort, the preflight below still fail-closes.
CANON="$( { grep '^TRADIER_ACCESS_TOKEN=' "$HOME/options-platform/.env" 2>/dev/null || true; } | head -1 | cut -d= -f2-)"
if [ -n "$CANON" ] && [ "$CANON" != "$(cat "$HOME/.tradier_token" 2>/dev/null)" ]; then
  printf '%s' "$CANON" > "$HOME/.tradier_token"
  chmod 600 "$HOME/.tradier_token"
  echo "tradier token: refreshed ~/.tradier_token from options-platform/.env"
fi

# 1-2) Refresh data + regenerate the dashboard blobs — CONFIG-DRIVEN, no script
#    edit needed. Put your one-line build command (data refresh + blob rebuild,
#    ending with index.html written into $REPO) in EITHER:
#      the SL_BLOB_BUILD_CMD environment variable, or
#      the file ~/.strategy_lab_build_cmd
#    Example (write once, from your local research session):
#      echo 'python3 build_dashboard.py --out ~/repos/strategy-lab/index.html' \
#        > ~/.strategy_lab_build_cmd
#    Until configured, the build runs in TRACK-ONLY mode: sell flags and the
#    indicator snapshot refresh daily, while scan/signal blobs stay at their
#    last build (the page's stamps show exactly this).
BUILD_CMD="${SL_BLOB_BUILD_CMD:-}"
[ -z "$BUILD_CMD" ] && [ -f "$HOME/.strategy_lab_build_cmd" ] && \
  BUILD_CMD="$(cat "$HOME/.strategy_lab_build_cmd")"
#    NON-FATAL, since 08/27. This script runs under `set -e`, so a failing
#    BUILD_CMD used to abort the entire build: no TRACK refresh, no publish, no
#    mail - the whole site frozen because one upstream generator broke. That is
#    the same silent-freeze the render gate caused between 08/19 and 08/26, and
#    it is inconsistent on its own terms: an UNCONFIGURED build_cmd degrades
#    gracefully to TRACK-only three lines below, so a BROKEN one should too.
#    The page already discloses stale SCAN/SIGNALS from the HEALTH stamp, so
#    falling back is visible rather than quiet.
if [ -n "$BUILD_CMD" ]; then
  echo "blob rebuild: $BUILD_CMD"
  if bash -c "$BUILD_CMD"; then
    echo "blob rebuild OK"
  else
    echo "WARNING: blob rebuild FAILED (rc=$?) - continuing in TRACK-only mode."
    echo "WARNING: SCAN and SIGNALS keep their previous values; the page's"
    echo "WARNING: freshness stamps will show it. Fix the generator."
  fi
else
  echo "blob rebuild not configured - TRACK-only build (see comments above)"
fi

# 3) Emit the TRACK inputs - READY TO RUN: closes fetched straight from
#    Tradier for every scan ticker + book-universe symbol parsed off the page.
#    Token: TRADIER_TOKEN env var or ~/.tradier_token file. ~6 min for ~700 names.
python3 "$REPO/scripts/dump_closes.py" --index "$REPO/index.html" \
  --out "$TMP/bars.json" --days 400 --ohlcv
# earnings.json (z-score force-exit + no-entry dates) - sourced from the local
# market-data-brain earnings cache (x37 fetcher format). Override the location
# with SL_EARNINGS_DIR; a missing dir just disables earnings flags (fail-quiet).
EARN_DIR="${SL_EARNINGS_DIR:-}"
if [ -z "$EARN_DIR" ]; then
  for d in "$HOME/Projects/market-data-brain/earnings" "$HOME/repos/market-data-brain/earnings"; do
    [ -d "$d" ] && EARN_DIR="$d" && break
  done
fi
# x45: the session-fetched MIO names have no brain earnings files yet, so a
# repo-committed seed (Robinhood calendar snapshot) fills only those symbols -
# the brain feed always wins where it has data. Refresh the brain side with
# scripts/lab_refetch_new_names.py --earnings to retire the seed.
# The seed was retired 2026-08-02: the Mac's Yahoo backfill populated the brain
# for 141 of the session-fetched names, so the brain feed now covers them.
python3 "$REPO/scripts/next_earnings.py" --dir "$EARN_DIR" --out "$TMP/earnings.json"

# 4) Splice the TRACK indicator snapshot into the page (ready to run).
python3 "$REPO/scripts/track_snapshot_reference.py" "$TMP/bars.json" \
  --earnings "$TMP/earnings.json" \
  --splice "$REPO/index.html" \
  --source "tradier local build $(date +%F)"

# 4b) Evaluate the strategy books' entry rules -> BOOKSIG (Gap Widen x2 +
#     Z-Score paper; BB dropped 2026-08-01 per its pre-registered kill gate).
python3 "$REPO/scripts/scan_book_signals.py" --bars "$TMP/bars.json" \
  --page "$REPO/index.html" --earnings "$TMP/earnings.json" --splice

# 4c) Shadow forward book - the automated skip-free paper ledger (fills queued
#     MOO entries, applies exit rules, logs today's qualifying TAKEs).
python3 "$REPO/scripts/shadow_book.py" --bars "$TMP/bars.json" \
  --page "$REPO/index.html" --earnings "$TMP/earnings.json" \
  --ledger "$REPO/data/shadow_book.json" --splice
# 4c2) ROBERT nightly scan -> static signals section spliced into robert.html
#      between the ROBSIG markers (fail-closed; universe = robert_universe.txt).
python3 "$REPO/scripts/robert_scan.py" --bars "$TMP/bars.json" \
  --earnings "$TMP/earnings.json" --page "$REPO/robert.html" \
  --universe "$REPO/robert_universe.txt" --splice
# 4c3) ROBERT shadow forward book - automatic stock-leg paper ledger.
python3 "$REPO/scripts/robert_shadow.py" --bars "$TMP/bars.json" \
  --earnings "$TMP/earnings.json" --page "$REPO/robert.html" \
  --universe "$REPO/robert_universe.txt" \
  --ledger "$REPO/data/robert_shadow.json" --splice

# 4d) Pipeline health stamp shown in the page header.
python3 - "$REPO/index.html" "$TMP/bars.json" "$TMP/earnings.json" <<'PYEOF'
import json, re, sys, datetime
page_path, bars_path, earn_path = sys.argv[1], sys.argv[2], sys.argv[3]
html = open(page_path).read()
bars = json.load(open(bars_path))
earn = json.load(open(earn_path))
scan = json.loads(re.search(r"const SCAN = (.*?);\n", html, re.S).group(1))
booksig = json.loads(re.search(r"const BOOKSIG = (.*?);\n", html, re.S).group(1))
shadow = json.loads(re.search(r"const SHADOW = (.*?);\n", html, re.S).group(1))
uni = len(json.loads(re.search(r"const TRACK = (.*?);\n", html, re.S).group(1)).get("tickers") or {}) or len(bars)
h = {"build": datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
     "bars_ok": len(bars), "universe": max(uni, len(bars)),
     "earnings": len(earn), "booksig_rows": len(booksig.get("rows") or []),
     "shadow_open": sum(1 for p in shadow.get("open") or [] if p.get("state") == "open"),
     "shadow_closed": shadow.get("closed_total") or 0}
line = "const HEALTH = " + json.dumps(h, separators=(",", ":")) + ";"
html2, n = re.subn(r"const HEALTH = .*?;\n", lambda _m: line + "\n", html, count=1, flags=re.S)
assert n == 1, "no HEALTH line"
open(page_path, "w").write(html2)
print("health stamped:", h)
PYEOF

# 5) Validate before publishing: every embedded blob must parse. Fail-closed.
python3 - "$REPO/index.html" <<'PYEOF'
import json, re, sys
html = open(sys.argv[1]).read()
for n in ["SCAN","BASKETS","SIGNALS","REGIME","DAILY","CALLS","TF","METHOD","BOOKS","TRACK","BOOKSIG","NOTIFY","SHADOW","HEALTH"]:
    m = re.search(r'const %s = (.*?);\n' % n, html, re.S)
    assert m, "missing blob: " + n
    json.loads(m.group(1))
track = json.loads(re.search(r'const TRACK = (.*?);\n', html, re.S).group(1))
assert track and track.get("tickers"), "TRACK is empty - refusing to publish"
assert "robert.html" in html, \
    "nav link to ROBERT missing - interface regressed, refusing to publish"
print("validation OK:", len(track["tickers"]), "tickers as of", track["as_of"])
PYEOF
python3 - "$REPO/robert.html" <<'PYCHK'
import sys
h = open(sys.argv[1]).read()
assert "ROBSIG:START" in h and "ROBSIG:END" in h, "robert.html ROBSIG markers missing"
assert "ROBSHADOW:START" in h and "ROBSHADOW:END" in h, "robert.html ROBSHADOW markers missing"
PYCHK

# 5b) RENDER GATE. smoke_test.js has been a hand-run script since it was
#     written: no workflow, no plist, no build step invoked it, so the 100+
#     assertions it carries have never blocked anything (audit 2026-08-18).
#     Its own header says exit codes were added "so anything wired to it could
#     block" - this is the wiring. The mail was already gated on
#     notify_test.py; the PAGE that mail links to was not gated on anything
#     beyond "the JSON parses".
#
#     Fail-closed, like every other validation above: a page whose render
#     assertions fail does not get published. If playwright is unavailable the
#     suite exits 2, which is NOT a pass - say so and refuse, rather than
#     letting a missing dependency read as a green run.
if command -v node >/dev/null 2>&1; then
  if node "$REPO/scripts/smoke_test.js"; then
    echo "render gate: smoke suite passed"
  else
    rc=$?
    if [ "$rc" = "2" ]; then
      echo "RENDER GATE UNAVAILABLE - playwright not installed (npm i -g playwright-core)."
      echo "Refusing to publish unverified. Install it or run with SKIP_RENDER_GATE=1."
    else
      echo "RENDER GATE FAILED (rc=$rc) - page assertions did not pass, refusing to publish."
    fi
    [ "${SKIP_RENDER_GATE:-0}" = "1" ] || exit 1
    echo "SKIP_RENDER_GATE=1 set - publishing anyway, on the operator's head."
  fi
else
  echo "RENDER GATE SKIPPED - node not on PATH."
  [ "${SKIP_RENDER_GATE:-0}" = "1" ] || exit 1
fi

# 6) Publish (GitHub Pages serves main, so push = deploy). The shadow ledger
#    is committed too - the forward record must survive machines.
cd "$REPO"
# robert_chain_snaps.json joined this list on 08/27: the build CAPTURES exit
# quotes now, and a snapshot written to a runner's disk and not committed
# dies with the runner - leaving a closed row in robert_shadow.json tagged
# CHAIN with no measurement behind it. Same defect the chain gate had when
# it stored a verdict without its thresholds: a number you cannot re-derive
# is a number you cannot defend.
git add index.html data/shadow_book.json robert.html \
  data/robert_shadow.json data/robert_chain_snaps.json
if git diff --cached --quiet; then
  echo "no changes to publish"
else
  git commit -m "daily build $(date +%F)"
  # `git push && break` is NOT the last command of its AND-list, so `set -e`
  # cannot see it fail. All five attempts could fail, the loop would end
  # normally, and both mails went out below - about a page that was never
  # published. notify_buys then writes its dedupe hash, so the corrected mail
  # would be suppressed as a duplicate and never sent at all. Verified
  # 2026-08-18: `set -euo pipefail; for d in 0 2; do false && break; done;
  # echo REACHED` prints REACHED and exits 0. This file's own header promises
  # "fail-closed: if any step or validation fails, nothing is pushed" - and the
  # cloud path already gets this right by gating on published == 'true'.
  pushed=0
  for delay in 0 2 4 8 16; do
    sleep "$delay"
    if git push origin main; then pushed=1; break; fi
  done
  if [ "$pushed" -ne 1 ]; then
    echo "PUSH FAILED after 5 attempts - page NOT published, holding all mail."
    echo "Nothing was sent. Fix the push, then re-run; the dedupe state is untouched."
    exit 1
  fi
  # 7) Notify (email + ntfy push + optional SMS) - configured via
  #    ~/.strategy_lab_notify.json, see docs/notifications.md. First harvest
  #    any self-service signups from the page's card. Never fails the build.
  python3 "$REPO/scripts/notify_signups.py" || echo "signup harvest failed (non-fatal)"
  # 7a) Gate the mail on rank consistency. The three surfaces that print a rank
  #     disagreed on 2026-08-18 - the digest sent a 16-trade row to the
  #     subscriber list as the day's #1 buy while the dashboard showed it
  #     unranked. A mail carrying a "buy at the open" imperative on numbers the
  #     page contradicts is worse than no mail, so this one gates rather than
  #     warning: same reasoning as the session-date gate inside notify_buys.
  if python3 "$REPO/scripts/notify_test.py"; then
    python3 "$REPO/scripts/notify_buys.py" --page "$REPO/index.html" \
      || echo "notify step failed (non-fatal)"
    # Simplified ranked digest to the wider list ("to_digest"). Chained here
    # rather than left to a clock so it can never read a half-written page: the
    # build is finished and pushed by the time this runs. The 16:00 launchd job
    # (com.alex.strategylab.digest) is a backstop for the days this step fails -
    # its own dedupe state makes a double-send impossible.
    python3 "$REPO/scripts/notify_buys.py" --page "$REPO/index.html" --simple \
      || echo "digest step failed (non-fatal)"
  else
    echo "RANK CONSISTENCY CHECK FAILED - no mail sent. The page is published;"
    echo "the buy mail is held because its ranks disagree with the dashboard's."
  fi
fi
echo "=== daily build done $(date '+%F %T') ==="
